### ISSUE TITLE
Possible to bump loader-utils to 1.x?

### ISSUE THREAD

**Issue by Leedehai** [gajus/to-string-loader#17]
Hi - I noticed to [loader-utils](https://www.npmjs.com/package/loader-utils) in the dependency is still 0.x version. Is it possible to bump it to 1.x (the current major version)?

**Comment by gajus** [comment]
If you bump it and it doesn't break anything, I will release it.

What is the reason for wanting to bump it though?

**Comment by Leedehai** [comment]
@gajus Because my org has a tools to warn about dependencies that are 0.x, which, according to [semver](https://semver.org/), is unstable.

I just checked out loader-utils [release notes](https://github.com/webpack/loader-utils/releases), and there's no breaking changes documented for the APIs used in to-string-loader.

Also, I just bumped the version to 1.2.3; it was fine.
