### ISSUE TITLE
Not working with url() or @import statements in stylesheets

### ISSUE THREAD

**Issue by noxan** [gajus/to-string-loader#2]
I struggled using this loader in combination with the `css-loader`. Just like written in the example of the readme file.

It works fine until you use a `url()` or `@import` statement which is translated into a `require()` statement. I guess the true issue is tracked here: https://github.com/webpack/webpack/issues/667

Just want to keep track of it here, since it took me hours of figuring out what is going wrong. Hope my assumptions about the origin of my issue are right. Would make my code for angular2 to such much nicer.

Workaround for me was to not use this loader, but to require the stylesheet and call `toString()` manually.

**Comment by JesusisFreedom** [comment]
How did you do it @noxan

**Comment by DontRelaX** [comment]
I will just leave it here: https://github.com/webpack/exports-loader
use it like
`loader: 'exports-loader?module.exports.toString()!css-loader'`
It will work perfect with url(). Don't forget about loader for images.

**Comment by noxan** [comment]
Has been a while ago, so I do not really remember the details. What worked for me was to define the loaders within the require statement and convert the result with the toString method.

I'm sorry but I do no more remember the details, has been quite a while ago... but this is how it worked for me in the end:
```
require('!css?root=.!stylus!./styles.styl').toString()
```

I will give @DontRelaX's solution a try as well, looks like this one might be working in the regular webpack config, too - thanks for your answer, mate!

**Comment by oocx** [comment]
I have a different implementation of a tostring-loader that also works with url():

```
var loaderUtils = require("loader-utils");
    
module.exports = function () {};
module.exports.pitch = function (remainingRequest) {
    if (this.cacheable) this.cacheable();
    
    return "module.exports = require(" + loaderUtils.stringifyRequest(this, "!!" + remainingRequest) + ").toString();";
};

```

This is based on the code in style-loader.

**Comment by mbaer3000** [comment]
oocx's solution works just fine for me, too. Thanks!

**Comment by juliangut** [comment]
@oocx I'm loving you right now, it works like a charm, wasted several hours today hunting this down

IMHO @gajus should update the loader as this is a major error

**Comment by inabhi9** [comment]
I found another plugin that deals with the same issue if anyone don't want to struggle or need ref: https://github.com/smithad15/css-to-string-loader

It works fine with me!

**Comment by thescientist13** [comment]
thanks @inabhi9 that worked for me!
