### ISSUE TITLE
Expected release for new `esModule` compatability?

### ISSUE THREAD

**Issue by localyost3000** [gajus/to-string-loader#21]
I was just writing a pull request to support esModules output by css-loader v4 until I saw that one has already been merged, last October. However, this code has not been released to npm yet.

I am currently disabling esModule from css-loader, but was wondering if an npm update is expected soon to support it.

Thanks!

**Comment by brunolemos** [comment]
Current workaround: `require('!!to-string-loader!css-loader?esModule=false!sass-loader!./index.scss')`

**Comment by SettingDust** [comment]
Current workaroud: `"to-string-loader": "github:gajus/to-string-loader"`

**Comment by gajus** [comment]
Published to-string-loader@1.2.0
